version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-3plcentral
            source /usr/local/share/virtualenvs/tap-3plcentral/bin/activate
            uv pip install .
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-3plcentral/bin/activate
            uv pip install pylint
            pylint tap_3plcentral --disable missing-docstring,logging-format-interpolation,no-member,broad-except,too-many-branches,trailing-whitespace,line-too-long,unnecessary-pass,useless-object-inheritance,too-many-instance-attributes,too-many-arguments,too-many-positional-arguments,consider-using-f-string,no-else-return,unused-import,unspecified-encoding,protected-access,too-many-locals,possibly-used-before-assignment

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
